### ISSUE TITLE
ClassNotFoundException: com.google.protobuf.GeneratedMessageV3

### ISSUE THREAD

**Issue by PratikBarhate** [combust/mleap#532]
We are trying to serialize an Apache Spark ML pipeline; which includes String Indexer, Standard Scalar, Vector Assembler, and Logistic Regression. (Serialization format JSON)
Apache Spark - v2.3.0
It works fine with MLeap - v0.12.0 but while using v0.13.0 we are facing the issue of a class not found; the class is from Google's Protobuf library. We tried to find out the Protobuf version used as the missing class seems to available on their latest master branch and the version found in our transitive dependencies pulled from maven is older, but we were unable to trace the issue.

The error stack is as follows:

>  Exception in thread "main" java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetPublicMethods(Class.java:2902)
	at java.lang.Class.getMethods(Class.java:1615)
	at spray.json.ProductFormats$class.extractFieldNames(ProductFormats.scala:72)
	at spray.json.DefaultJsonProtocol$.extractFieldNames(DefaultJsonProtocol.scala:30)
	at spray.json.ProductFormatsInstances$class.jsonFormat2(ProductFormatsInstances.scala:43)
	at spray.json.DefaultJsonProtocol$.jsonFormat2(DefaultJsonProtocol.scala:30)
	at ml.combust.bundle.json.JsonSupport$class.$init$(JsonSupport.scala:82)
	at ml.combust.bundle.json.JsonSupport$.<init>(JsonSupport.scala:295)
	at ml.combust.bundle.json.JsonSupport$.<clinit>(JsonSupport.scala)
	at ml.combust.bundle.serializer.JsonFormatModelSerializer.write(ModelSerializer.scala:48)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply$mcV$sp(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply(ModelSerializer.scala:89)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2.apply(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2.apply(ModelSerializer.scala:89)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:31)

**Comment by PratikBarhate** [comment]
I tried manually deleting the protobuf-java:2.5.0 and all the other 2.x.x versions from the m2 repository, but still, maven pulls the v2.5.0 into the dependencies while the required version seems to be 3.5.0. 

Any suggestions on what can be the reason for the same?

**Comment by rucarden** [comment]
Did you resolve your issue?  How are you managing your dependencies.  Are you using gradle or sbt?

**Comment by PratikBarhate** [comment]
Not we were not able to resolve the issue we went ahead with prototyping with v0.12.0. We are using maven v3.53

**Comment by ancasarb** [comment]
@PratikBarhate could you please check out this issue https://github.com/combust/mleap/issues/479? it sounds similar to what you're seeing. I believe it was the spark-sql_2.11 that was bringing in protobuf-java:2.5.0, depending on what you're using (maven, gradle, sbt) there are ways to exclude that. 

Hope this helps!

**Comment by PratikBarhate** [comment]
@ancasarb Thank you, the solution presented in the issue [#479](https://github.com/combust/mleap/issues/479) solved it as it seems to be the same issue.
