### ISSUE TITLE
Spark 3.0

### ISSUE THREAD

**Issue by Ben-Epstein** [combust/mleap#727]
Hello, 

I see you have a spark3.0 branch in the works, but it hasn't been looked at in a while. Do you have a time estimate of it's release, or an estimate of the amount of work needed to get it ready?

**Comment by mleida-stratio** [comment]
Also do you know if the spark3.0 branch is functional? I see it's passing the ci workflow successfully.

**Comment by Ben-Epstein** [comment]
Hi @ancasarb is there any update on spark 3?

**Comment by vvavepacket** [comment]
@Ben-Epstein 

If it seems there are no immediate plans to merge Spark 3.0 functionality to master, whats your backup plan to deploy your Spark 3 models outside Spark? It seems there is mlflow, but it mainly supports Python (assuming you depend on Java/Scala).

**Comment by Ben-Epstein** [comment]
> @Ben-Epstein
> 
> If it seems there are no immediate plans to merge Spark 3.0 functionality to master, whats your backup plan to deploy your Spark 3 models outside Spark? It seems there is mlflow, but it mainly supports Python (assuming you depend on Java/Scala).

@vvavepacket I have been testing with spark 3.0, scala 2.12 on mleap 0.16.0 and I haven't found any problems (yet). My backup is to try to build my own distro from their spark 3.0 branch. Did you run into any particular issues trying mleap 0.16.0 with spark3.0? There weren't many changes from the SparkML side.

**Comment by vvavepacket** [comment]
@Ben-Epstein  to be honest i never tried it with Spark 3.0 since I saw on readme its not supported. but ill try and give it a shot... hope it works

**Comment by Ben-Epstein** [comment]
@vvavepacket I just finished my testing and found the MultiLayerPerceptronClassifier failed to `serializeToBundle` but all others tested models passed. For my team at least, this is not a blocker and we're moving forward. Happy to keep posted findings here if you're interested. I'd love to see your findings as well

**Comment by vvavepacket** [comment]
@Ben-Epstein I was using `MultiLayerPerceptronClassifier` and it failed with the same error so its a blocker for me. Guess its an unlucky day for me. Thanks for cross posting our results though

**Comment by Ben-Epstein** [comment]
@vvavepacket you can try to build their 3.0 branch, it might just work

**Comment by vvavepacket** [comment]
> @vvavepacket you can try to build their 3.0 branch, it might just work

Nope it did not work.

**Comment by talalryz** [comment]
could you share the error you're getting when using the spark 3.0 branch?

**Comment by jsleight** [comment]
I've been trying to use latest mleap in spark v3 and there are several changes that need to made (which are not included in the spark v3 branch either).  The biggest source of problems that I encountered is that spark v3 altered several feature transformers to support both single column (via inputCol and outputCol) and multi-column (via inputCols and outputCols) formats.  So all of those features will need to have their mleap code adjusted.

**Comment by Ben-Epstein** [comment]
@jsleight which transformers are you seeing problems with on serialization? Are you using mleap 0.16.0?

**Comment by Ben-Epstein** [comment]
@ancasarb is mleap still being maintained? I saw you updated the release notes for 0.17.0, is that supposed to have spark3? Would community support help move things along?

**Comment by ancasarb** [comment]
@Ben-Epstein @jsleight @vvavepacket  hi all! 

Yes, we are working on updating the Spark 3.0 so that we can merge it in. i am hoping to get this done in the next couple of weeks, it's been a WIP at the moment.

**Comment by jsleight** [comment]
> @jsleight which transformers are you seeing problems with on serialization? Are you using mleap 0.16.0?

I'm using mleap 0.17 daily snapshot based on current master branch.  The transformers that sometimes don't serialize are the one that now support both inputCol/outputCol and inputCols/outputCols.  E.g., Bucketizer won't serialize if you use the inputCols/outputCols API, but does serialize if you use the inputCol/outputCol API.  Even in the mleap spark v3 branch, this issue would still occur (just by inspecting the spark BucketizerOp)-- we need to make the test suite more robust to cover these new transformer capabilities.

**Comment by emitc2h** [comment]
Hey folks, are there any updates worth publishing to the `spark-3.0.0 branch`? We're trying to migrate Transmogrif.ai to scala 2.12 and Spark 3, and we're suspecting some of our unit tests failures can be traced back to mleap. I would just like to build Transmogrif.ai against a version of mleap that can at least compile with Spark 3 and scala 2.12.

**Comment by jsleight** [comment]
Current master does compile with scala 2.12 and spark 3, but there are some correctness things (see my comments above) to watch out for.

**Comment by emitc2h** [comment]
> Current master does compile with scala 2.12 and spark 3, but there are some correctness things (see my comments above) to watch out for.

Currently in the master branch the spark version is still 2.4.5 and the scala version is still 2.11. I've tried changing the spark version and the scala version in `project/Dependencies.scala` and `project/Common.scala`, but it's not enough to make it compile. I'm seeing not only dependency conflicts, but also all sorts of errors due to API changes (in breeze.linalg for example). What am I missing?

**Comment by jsleight** [comment]
> > Current master does compile with scala 2.12 and spark 3, but there are some correctness things (see my comments above) to watch out for.
> 
> Currently in the master branch the spark version is still 2.4.5 and the scala version is still 2.11. I've tried changing the spark version and the scala version in `project/Dependencies.scala` and `project/Common.scala`, but it's not enough to make it compile. I'm seeing not only dependency conflicts, but also all sorts of errors due to API changes (in breeze.linalg for example). What am I missing?

Ah sorry, what I meant was if you compile current master branch to produce the jar, then you can install that jar into a Spark 3 project and it will run "correctly" (sans things already mentioned in this thread).  Obviously this is unsafe in multiple ways, but does pseudo-work as a stopgap.

**Comment by emitc2h** [comment]
Thanks for the clarification @jsleight. I'll try what you suggest.

**Comment by emitc2h** [comment]
Hi @jsleight, what you suggest works in terms of allowing Transmogrif.ai to compile. However, regardless of whether I compile it with Spark 2.4.5/scala 2.11 or Spark 3.1.1/scala 2.12, I'm seeing a number of our unit tests failing due to the following error:
```
scala/Product$class
java.lang.NoClassDefFoundError: scala/Product$class
	at ml.combust.bundle.BundleRegistry.<init>(BundleRegistry.scala:73)
	at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:73)
	at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:44)
	at ml.combust.bundle.BundleRegistry$.apply(BundleRegistry.scala:28)
	at org.apache.spark.ml.bundle.SparkBundleContext$.apply(SparkBundleContext.scala:21)
	at org.apache.spark.ml.bundle.SparkBundleContext$.apply(SparkBundleContext.scala:17)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParams.setStageSavePath(SparkWrapperParams.scala:118)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParams.setStageSavePath$(SparkWrapperParams.scala:115)
	at com.salesforce.op.stages.sparkwrappers.generic.SwUnaryEstimator.setStageSavePath(SwUnaryEstimator.scala:58)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParamsTest.$anonfun$new$2(SparkWrapperParamsTest.scala:60)
	at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1682)
	at org.scalatest.TestSuite.withFixture(TestSuite.scala:196)
	at org.scalatest.TestSuite.withFixture$(TestSuite.scala:195)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.invokeWithFixture$1(FlatSpecLike.scala:1680)
	at org.scalatest.FlatSpecLike.$anonfun$runTest$1(FlatSpecLike.scala:1692)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:289)
	at org.scalatest.FlatSpecLike.runTest(FlatSpecLike.scala:1692)
	at org.scalatest.FlatSpecLike.runTest$(FlatSpecLike.scala:1674)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParamsTest.org$scalatest$BeforeAndAfterEach$$super$runTest(SparkWrapperParamsTest.scala:43)
	at org.scalatest.BeforeAndAfterEach.runTest(BeforeAndAfterEach.scala:221)
	at org.scalatest.BeforeAndAfterEach.runTest$(BeforeAndAfterEach.scala:214)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParamsTest.runTest(SparkWrapperParamsTest.scala:43)
	at org.scalatest.FlatSpecLike.$anonfun$runTests$1(FlatSpecLike.scala:1750)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:396)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:373)
	at org.scalatest.SuperEngine.$anonfun$runTestsInBranch$1(Engine.scala:410)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:384)
	at org.scalatest.SuperEngine.runTestsInBranch(Engine.scala:379)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:461)
	at org.scalatest.FlatSpecLike.runTests(FlatSpecLike.scala:1750)
	at org.scalatest.FlatSpecLike.runTests$(FlatSpecLike.scala:1749)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1685)
	at org.scalatest.Suite.run(Suite.scala:1147)
	at org.scalatest.Suite.run$(Suite.scala:1129)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1685)
	at org.scalatest.FlatSpecLike.$anonfun$run$1(FlatSpecLike.scala:1795)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:521)
	at org.scalatest.FlatSpecLike.run(FlatSpecLike.scala:1795)
	at org.scalatest.FlatSpecLike.run$(FlatSpecLike.scala:1793)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParamsTest.org$scalatest$BeforeAndAfterAll$$super$run(SparkWrapperParamsTest.scala:43)
	at org.scalatest.BeforeAndAfterAll.liftedTree1$1(BeforeAndAfterAll.scala:213)
	at org.scalatest.BeforeAndAfterAll.run(BeforeAndAfterAll.scala:210)
	at org.scalatest.BeforeAndAfterAll.run$(BeforeAndAfterAll.scala:208)
	at com.salesforce.op.stages.sparkwrappers.generic.SparkWrapperParamsTest.run(SparkWrapperParamsTest.scala:43)
	at org.scalatest.junit.JUnitRunner.run(JUnitRunner.scala:99)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:32)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:175)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:157)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:404)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: scala.Product$class
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 84 more
```
Any code of ours that touches the BundleRegistry seems to throw this error. Have you seen this before?

**Comment by jsleight** [comment]
That usually indicates that you don't have mleap's `reference.conf` file included.  You need to use an append strategy in a maven/sbt plugin to make sure that file gets included.
