### ISSUE TITLE
Saving bundle generates error: java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3

### ISSUE THREAD

**Issue by samikrc** [combust/mleap#479]
After updating from mleap v0.11.0 to v0.13.0, I am getting the following exception when I try to save a Spark model:
```
A needed class was not found. This could be due to an error in your runpath. Missing class: com/google/protobuf/GeneratedMessageV3
java.lang.NoClassDefFoundError: com/google/protobuf/GeneratedMessageV3
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        ...
	at ml.combust.bundle.json.JsonSupport$class.$init$(JsonSupport.scala:82)
	at ml.combust.bundle.json.JsonSupport$.<init>(JsonSupport.scala:295)
	at ml.combust.bundle.json.JsonSupport$.<clinit>(JsonSupport.scala)
	at ml.combust.bundle.serializer.JsonFormatModelSerializer.write(ModelSerializer.scala:48)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply$mcV$sp(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2$$anonfun$apply$1.apply(ModelSerializer.scala:89)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2.apply(ModelSerializer.scala:89)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$2.apply(ModelSerializer.scala:89)
	at scala.util.Success.flatMap(Try.scala:231)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:88)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:34)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$writeNode$1.apply(GraphSerializer.scala:30)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.GraphSerializer.writeNode(GraphSerializer.scala:30)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at ml.combust.bundle.serializer.GraphSerializer$$anonfun$write$2.apply(GraphSerializer.scala:21)
	at scala.collection.IndexedSeqOptimized$class.foldl(IndexedSeqOptimized.scala:57)
	at scala.collection.IndexedSeqOptimized$class.foldLeft(IndexedSeqOptimized.scala:66)
	at scala.collection.mutable.WrappedArray.foldLeft(WrappedArray.scala:35)
	at ml.combust.bundle.serializer.GraphSerializer.write(GraphSerializer.scala:20)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:21)
	at org.apache.spark.ml.bundle.ops.PipelineOp$$anon$1.store(PipelineOp.scala:14)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:87)
	at ml.combust.bundle.serializer.ModelSerializer$$anonfun$write$1.apply(ModelSerializer.scala:83)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.ModelSerializer.write(ModelSerializer.scala:83)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:85)
	at ml.combust.bundle.serializer.NodeSerializer$$anonfun$write$1.apply(NodeSerializer.scala:81)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.NodeSerializer.write(NodeSerializer.scala:81)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:34)
	at ml.combust.bundle.serializer.BundleSerializer$$anonfun$write$1.apply(BundleSerializer.scala:29)
	at scala.util.Try$.apply(Try.scala:192)
	at ml.combust.bundle.serializer.BundleSerializer.write(BundleSerializer.scala:29)
	at ml.combust.bundle.BundleWriter.save(BundleWriter.scala:31)
	at com.tfs.test.MleapPipelineTest$$anonfun$2.apply(MleapPipelineTest.scala:88)
        ...
```

This message is generated from the following code block:
```
    val sbc = SparkBundleContext().withDataset(model.transform(smallDF))
    for(bf <- managed(BundleFile(s"jar:file:${file.getPath}")))
    {   model.writeBundle.save(bf)(sbc).get }    //Line# 88 MleapPipelineTest.scala
```

I investigated this some more, and looks like, at the moment the following gets pulled in as external library: `Maven: com.google.protobuf:protobuf-java:2.5.0`
It also looks like the com/google/protobuf/GeneratedMessageV3 is available from protobuf-java 3.1.0 onwards (https://github.com/google/safe-html-types/issues/1). I am not able to figure out how this specific version (2.5.0) is getting pulled, and where I should update so that the correct version gets pulled.

Anyone else gets this error? Any pointers.
Thanks.

**Comment by ancasarb** [comment]
hey @samikrc i'll try to reproduce this, what are the transformers included in your pipeline?

**Comment by samikrc** [comment]
Hello, thanks for your response. Code in the following repo shows the issue: https://github.com/samikrc/try-mleap/
Specifically running the following two tests throws the exception mentioned:

- CommonModelsSpec
- MleapPipelineTest

CommonModelsSpec is actually a collection of lot of small pipelines, the first one of which contains a Tokenizer, HashingTF and IDF.

**Comment by samikrc** [comment]
Realized that other than updating to mleap 0.13, I have also updated to Spark 2.4. But reverting back to older Spark version did not seem to matter - still get the same exception.

**Comment by ancasarb** [comment]
ok, cool, I'm taking a look at your tests.

**Comment by ancasarb** [comment]
Okay, it's spark-sql_2.11 dependency that's actually bringing in the protobuf 2.5 dependency. I think you can just remove it entirely (I couldn't really see where it was needed?) or alternatively you can include it like this in Maven.

```
        <dependency>
            <groupId>org.apache.spark</groupId>
            <artifactId>spark-sql_2.11</artifactId>
            <version>2.3.0</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.protobuf</groupId>
                    <artifactId>protobuf-java</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

With this change, most of the tests in CommonModelsSpec are passing. 

Just a note on OneHotEncoder, because it's deprecated in Spark 2.3 and will be removed from Spark soon, you should use OneHotEncoderEstimator instead. It works pretty similarly to the deprecated one. MLeap 0.13.0 only has support for OneHotEncoderEstimator, older MLeap versions will have some support older versions of Spark and OneHotEncoder, but just updating to use OneHotEncoderEstimator should be okay. 

Let me know if you have any questions!

**Comment by samikrc** [comment]
Hello, thanks for the note - much appreciated. I will check this out and get back. Will also update the OHE part.

Curious, can you provide a few lines about how you arrived at the dependency? I tried out using dependency analyzer in IntelliJ but was not able to get it.

Thanks again.

**Comment by samikrc** [comment]
Ok - found the answer to above with some heavy-duty web search. The following command shows the information I am looking for:
```
try-mleap$ mvn dependency:tree -Dincludes=com.google.protobuf:protobuf-java
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building try-mleap 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ try-mleap ---
[INFO] com.tfs.test:try-mleap:jar:1.0-SNAPSHOT
[INFO] \- org.apache.spark:spark-sql_2.11:jar:2.4.0:compile
[INFO]    \- org.apache.orc:orc-core:jar:nohive:1.5.2:compile
[INFO]       \- com.google.protobuf:protobuf-java:jar:2.5.0:compile
```
Will get back on the rest.

**Comment by ancasarb** [comment]
Yep, that's the one I used as well.

**Comment by samikrc** [comment]
Tried this out today. I had to exclude protobuf-java from spark-yarn as well, and then the correct version got pulled in through mleap, as shown below.
```
try-mleap$ mvn dependency:tree -Dincludes=com.google.protobuf:protobuf-java
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building try-mleap 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ try-mleap ---
[INFO] com.tfs.test:try-mleap:jar:1.0-SNAPSHOT
[INFO] \- ml.combust.mleap:mleap-runtime_2.11:jar:0.13.0:compile
[INFO]    \- ml.combust.bundle:bundle-ml_2.11:jar:0.13.0:compile
[INFO]       \- com.google.protobuf:protobuf-java:jar:3.5.1:compile
[INFO] ------------------------------------------------------------------------
```

This takes care of the issue mentioned here. However, then I got stuck with #423, a completely unrelated issues. Will follow-up on that separately. Closing this issue.
